# Generated by Django 2.2 on 2021-05-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0002_auto_20210525_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_shoe', to='sneaker_app.User'),
        ),
    ]
