# Generated by Django 2.2 on 2021-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0003_auto_20210525_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='release_year',
            field=models.DateTimeField(),
        ),
    ]
