# Generated by Django 2.2 on 2021-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0005_auto_20210528_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='release_date',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
