# Generated by Django 2.2 on 2021-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0006_auto_20210528_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='release_year',
            field=models.DateField(verbose_name='%B %d %Y'),
        ),
    ]
