# Generated by Django 2.2 on 2021-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0008_auto_20210531_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='release_year',
            field=models.DateTimeField(),
        ),
    ]
