# Generated by Django 2.2 on 2021-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0009_auto_20210531_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='release_year',
            field=models.DateField(),
        ),
    ]
