# Generated by Django 2.2 on 2021-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0010_auto_20210531_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='img',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
