# Generated by Django 2.2 on 2021-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0011_sneaker_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='img',
            field=models.TextField(default=None, null=True),
        ),
    ]
