# Generated by Django 2.2 on 2021-06-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0012_auto_20210602_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sneaker_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_review', to='sneaker_app.Sneaker'),
            preserve_default=False,
        ),
    ]
