# Generated by Django 2.2 on 2021-06-10 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0013_review_sneaker_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sneaker_review',
        ),
        migrations.AddField(
            model_name='review',
            name='sneaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sneaker_app.Sneaker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_reviews', to='sneaker_app.User'),
        ),
    ]
